name: twoalogistic_shared
description: Shared models and utilities for 2A Logistic applications
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
